routes/web.php
<?php

use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function () {
        Route::post('livewire/message/{name}', '\Livewire\Controllers\HttpConnectionHandler');

        Route::get('login', \App\Http\Livewire\Auth\Login::class)
            ->middleware('guest')
            ->name('login');

        Route::get('home', \App\Http\Livewire\Home::class)
            ->name('home');

        Route::get('teams', \App\Http\Livewire\Team::class)
            ->name('teams');

        Route::get('user', \App\Http\Livewire\User::class)
            ->name('user');

        Route::get('coursetype', \App\Http\Livewire\CourseType::class)
            ->name('coursetype');

        Route::get('course', \App\Http\Livewire\Course::class)
            ->name('course');

        Route::get('participant/{course}', \App\Http\Livewire\CourseParticipant::class)
            ->name('participant.course');

        Route::get('participant/{participant}/details', \App\Http\Livewire\ParticipantDetails::class)
            ->name('participant.details');

        Route::get('participant', \App\Http\Livewire\Participant::class)
            ->name('participant');

        Route::get('roles', \App\Http\Livewire\Role::class)
            ->name('roles');

        Route::get('prices', \App\Http\Livewire\Price::class)
            ->name('prices');

        Route::get('positions', \App\Http\Livewire\Position::class)
            ->name('positions');

        Route::get('cert-templates', \App\Http\Livewire\CertTemplate::class)
            ->name('certTemplates');

        Route::get('password/reset/{hashedId}', \App\Http\Livewire\PasswordReset::class)
            ->middleware('signed')
            ->name('password.reset');

        Route::get('course/{slug}', \App\Http\Livewire\LocationSearch::class);

        Route::get('course/{slug}/{location}', \App\Http\Livewire\BookingOverview::class)
            ->name('booking.overview');

        Route::get('course/{slug}/{location}/{location2}', \App\Http\Livewire\BookingOverview::class)
            ->name('booking.coordinates');

        Route::get('booking/{course}/{price}', \App\Http\Livewire\Booking::class)
            ->name('booking');
    }
);

if (config('services.indexnow.key')) {
    Route::get('{key}.txt', function (Request $request, $key) {
        if ($key === config('services.indexnow.key')) {
            return config('services.indexnow.key');
        }

        abort(404);
    });
}

Route::get('/', function () {
    return redirect(config('app.redirect'));
});

Route::get('setup', \App\Http\Livewire\Setup::class);

Route::get('coordinates', [App\Http\Controllers\CoordinatesController::class, 'import']);
Route::get('locations', [App\Http\Controllers\CoordinatesController::class, 'locations']);

Route::get(
    '/email/verify',
    function () {
        return view('auth.verify-email'); // TODO correct message if still not confirmed email
    }
)
    ->middleware('auth')
    ->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect()->to('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return redirect()->back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

app/Http/Livewire/Booking.php
<?php

namespace App\Http\Livewire;

use App\Events\CourseBooked;
use App\Models\ContactPerson;
use App\Models\Course;
use App\Models\Participant;
use App\Models\Price;
use Carbon\Carbon;
use Illuminate\Contracts\Database\Query\Builder;
use Livewire\Component;
use Vinkla\Hashids\Facades\Hashids;

class Booking extends Component
{
    public bool $samePerson = true;
    public bool $bookingSuccessful = false;
    public string $course;
    public string $price;
    public string $payment = '';
    public array $participants = [[]];
    public array $contactPerson = [];

    protected function rules(): array
    {
        return [
            'contactPerson.company' => 'sometimes',
            'contactPerson.firstname' => 'required',
            'contactPerson.lastname' => 'required',
            'contactPerson.street' => 'required',
            'contactPerson.zipcode' => 'required',
            'contactPerson.location' => 'required',
            'contactPerson.email' => 'required',
            'contactPerson.phone' => 'required',
            'participants.*.firstname' => 'required',
            'participants.*.lastname' => 'required',
            'participants.*.date_of_birth' => 'required',
        ];
    }

    public function mount() // needed to make $this->course available automatically
    {
    }

    public function addParticipant()
    {
        $this->participants = array_filter($this->participants); // remove empty values
        $this->participants[] = [];
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
    }

    public function updatedContactPersonCompany()
    {
        if ($this->contactPerson['company'] === '') {
            unset($this->contactPerson['company']);
        }
    }

    public function updatedContactPerson($value, $field)
    {
        // update participant if is same person and contact person is updated
        if ($this->samePerson) {
            if ($field == 'firstname') {
                $this->participants[0]['firstname'] = $value;
            }

            if ($field == 'lastname') {
                $this->participants[0]['lastname'] = $value;
            }

            if ($field == 'email') {
                $this->participants[0]['email'] = $value;
            }

            if ($field == 'phone') {
                $this->participants[0]['phone'] = $value;
            }
        }
    }

    public function removeParticipant($participant)
    {
        unset($this->participants[$participant]);
        $this->participants = array_values($this->participants);
    }

    public function save($course_id, $price_id, $team_id)
    {
        $this->participants = array_filter($this->participants); // remove empty values

        $this->validate();

        // get the amount and currency
        $amount = Price::whereId($price_id)->first();

        if (
            // check if the contact person is the participant
            $this->samePerson &&
            count($this->participants) === 1 &&
            $this->participants[0]['lastname'] == $this->contactPerson['lastname'] &&
            $this->participants[0]['firstname'] == $this->contactPerson['firstname']
        ) {
            $participant = Participant::create([
                'course_id' => $course_id,
                'contact_id' => null,
                'team_id' => $team_id,
                'lastname' => $this->contactPerson['lastname'],
                'firstname' => $this->contactPerson['firstname'],
                'date_of_birth' => Carbon::parse($this->participants[0]['date_of_birth'])->isoFormat('YYYY-MM-DD'),
                'company' => $this->contactPerson['company'] ?? '',
                'street' => $this->contactPerson['street'],
                'zipcode' => $this->contactPerson['zipcode'],
                'location' => $this->contactPerson['location'],
                'phone' => $this->contactPerson['phone'],
                'email' => $this->contactPerson['email'],
                'price_net' => $amount->amount_net,
                'price_gross' => $amount->amount_gross,
                'currency' => $amount->currency,
                'payment' => $this->payment,
                'price_id' => $price_id,
            ]);

            event(new CourseBooked($participant, app()->getLocale()));
        } else { // contact person != participant(s)
            // create contact person
            $contactPerson = ContactPerson::create([
                'team_id' => $team_id,
                'lastname' => $this->contactPerson['lastname'],
                'firstname' => $this->contactPerson['firstname'],
                'company' => $this->contactPerson['company'] ?? '',
                'street' => $this->contactPerson['street'],
                'zipcode' => $this->contactPerson['zipcode'],
                'location' => $this->contactPerson['location'],
                'phone' => $this->contactPerson['phone'],
                'email' => $this->contactPerson['email'],
            ]);

            $participants = [];

            // some preparation for bulk insert
            foreach ($this->participants as $participant) {
                $participant['course_id'] = $course_id;
                $participant['contact_id'] = $contactPerson->id;
                $participant['team_id'] = $team_id;
                $participant['date_of_birth'] = Carbon::parse($participant['date_of_birth'])->isoFormat('YYYY-MM-DD');
                $participant['company'] = $this->contactPerson['company'] ?? '';
                $participant['email'] = $participant['email'] ?? '';
                $participant['phone'] = $participant['phone'] ?? '';
                $participant['price_net'] = $amount->amount_net;
                $participant['price_gross'] = $amount->amount_gross;
                $participant['currency'] = $amount->currency;
                $participant['payment'] = $this->payment;
                $participant['price_id'] = $price_id;
                $participant['created_at'] = Carbon::now();
                $participant['updated_at'] = Carbon::now();
                $participants[] = $participant;
            }

            $participant = Participant::insert(
                $participants
            );
        }

        if ($participant) { // success
            $this->bookingSuccessful = true;
        }
    }

    public function render()
    {
        $course_data = Course::where('id', '=', Hashids::decode($this->course))
            ->where('public_bookable', '=', 1)
            ->where('start', '>', Carbon::now()->subDays(31))
            ->whereRelation('prices', 'id', '=', Hashids::decode($this->price))
            ->with('type')
            ->with(['prices' => fn ($query) => $query->where('id', '=', Hashids::decode($this->price))])
                ->whereHas('prices', function (Builder $query) {
                    $query->where('id', '=', Hashids::decode($this->price));
                })
            ->withCount(['participants' => fn ($query) => $query->where('cancelled', 0)])
            ->firstOrFail();

        $prices = $course_data->relationsToArray()['prices'][0];

        // (pre)select payment method, if it's only one
        if (count(unserialize($prices['payment'])) === 1) {
            $this->payment = array_key_first(unserialize($prices['payment']));
        }

        $index = true;

        if ($course_data['start'] < Carbon::now()) { // meta noindex if the course start is in the past
            $index = false;
        }

        return view('livewire.booking', [
            'course_data' => $course_data,
        ])
            ->layout('layouts.booking', [
                'metaTitle' => _i('Book course'),
                'index' => $index,
            ]);
    }
}

app/Http/Livewire/BookingOverview.php
<?php

namespace App\Http\Livewire;

use App\Models\Coordinates;
use App\Models\Course;
use App\Models\CourseType;
use Carbon\Carbon;
use Livewire\Component;
use Vinkla\Hashids\Facades\Hashids;

class BookingOverview extends Component
{
    public bool $showPriceModal = false;
    public string $courseType;
    public string $slug;
    public string $location;
    public string $location2;
    public string $lat;
    public string $lon;
    public Course $actual;

    public array $searchLocations = [];

    public function mount()
    {
        $courseType = CourseType::whereSlug($this->slug)->firstOrFail();
        $this->courseType = $courseType->name;

        if (isset($this->location2) && is_numeric($this->location) && is_numeric($this->location2)) {
            $this->lat = $this->location;
            $this->lon = $this->location2;
        }

        if (! isset($this->lat) || ! isset($this->lon)) { // no coordinates set, yet
            if (isset($this->location2)) {
                $this->location = $this->location . '/' . $this->location2;
            }

            $coordinates = Coordinates::whereLocation($this->location)->firstOrFail();

            $this->lat = $coordinates->lat;
            $this->lon = $coordinates->lon;
        }

        $this->actual = new Course();
    }

    public function showPrice(Course $actual)
    {
        $this->actual = $actual;
        $this->showPriceModal = true;
    }

    public function selectCourse($course, $price)
    {
        return redirect()->route('booking', ['course' => Hashids::encode($course), 'price' => Hashids::encode($price)]);
    }

    public function render()
    {
        $perimeter_locations = $this->perimeterSearch($this->lat, $this->lon, 50); // all locations in the perimeter

        // all locations in the perimeter with bookable courses
        $possible_locations = Course::where('public_bookable', 1)
            ->where('start', '>', Carbon::now())
            ->whereIn('location', $perimeter_locations->pluck('location'))
            ->get();

        // remove the locations without course from the perimeter result
        $i = 0;
        foreach ($perimeter_locations as $perimeter) {
            if (! in_array($perimeter['location'], $possible_locations->pluck('location')->toArray())) {
                unset($perimeter_locations[$i]);
            }
            $i++;
        }

        $this->searchLocations = array_filter($this->searchLocations);

        if (empty($this->searchLocations) && $perimeter_locations->isNotEmpty()) { // no course location selected
            $found = false;
            foreach ($perimeter_locations as $location) {
                if ($location->distance <= 15) { // select courses < 15 km
                    $this->searchLocations[$location->location] = $location->location;
                    $found = true;
                }
            }

            if (! $found) { // no course < 15 km
                foreach ($perimeter_locations as $location) {
                    if ($location->distance <= 25) { // select courses < 25 km
                        $this->searchLocations[$location->location] = $location->location;
                        $found = true;
                    }
                }
            }

            if (! $found) { // no course < 25 km
                // select the first result
                $this->searchLocations[$perimeter_locations->first()->location] =
                    $perimeter_locations->first()->location
                ;
            }
        }

        $courses = Course::where('public_bookable', 1)
            ->where('start', '>', Carbon::now())
            ->where('cancelled', '=', null)
            ->whereIn('location', $this->searchLocations)
            ->with('prices')
            ->with('type')
            ->withCount(['participants' => fn ($query) => $query->where('cancelled', 0)])
            ->get();

        return view('livewire.booking-overview', [
            'perimeter_locations' => $perimeter_locations,
            'courses' => $courses,
        ])
            ->layout('layouts.booking', [
                'metaTitle' => $this->courseType . ' ' . (is_numeric($this->location)
                        ? _i('near you')
                        : _i('in %s and surroundings', $this->location)),
                'index' => true,
            ]);
    }

    public function perimeterSearch($lat, $lon, $max = 25)
    {
        $max = $max * 1000; // distance in km

        return Coordinates::selectRaw("`location`, ST_Distance_Sphere(
                    Point($lon, $lat),
                    Point(lon, lat)
                ) * ? as distance", [.001])
            ->whereRaw("ST_Distance_Sphere(
                    Point($lon, $lat),
                    Point(lon, lat)
                 ) <  ? ", $max)
            ->orderBy('distance')
            ->get();
    }
}

app/Http/Livewire/DataTable/WithCachedRows.php
<?php

namespace App\Http\Livewire\DataTable;

trait WithCachedRows
{
    protected bool $useCache = false;

    public function useCachedRows()
    {
        $this->useCache = true;
    }

    public function cache($callback): mixed
    {
        $cacheKey = $this->id;

        if ($this->useCache && cache()->has($cacheKey)) {
            return cache()->get($cacheKey);
        }

        $result = $callback();

        cache()->put($cacheKey, $result);

        return $result;
    }
}

app/Http/Livewire/DataTable/WithPerPagePagination.php
<?php

namespace App\Http\Livewire\DataTable;

use Livewire\WithPagination;

trait WithPerPagePagination
{
    use WithPagination;

    public int $perPage = 10;

    public function mountWithPerPagePagination()
    {
        $this->perPage = session()->get('perPage', $this->perPage);
    }

    public function updatedPerPage($value)
    {
        session()->put('perPage', $value);
    }

    public function applyPagination($query): mixed
    {
        return $query->paginate($this->perPage);
    }
}

resources/views/livewire/booking-overview.blade.php
<div>
    <div>
        <div class="max-w-7xl mx-auto py-4 px-4 sm:py-6 sm:px-6 lg:px-8">
            <div class="text-center">
                <h1 class="text-base font-semibold text-indigo-600 tracking-wide uppercase">{{ _i('Course overview') }}</h1>
                <p class="max-w-xl mt-5 mx-auto text-xl text-gray-500">{{ $courseType }} {{ (is_numeric($location) ? _i('near you') : _i('in %s and surroundings', $location)) }}</p>
            </div>
        </div>
    </div>

    <fieldset class="space-x-5">
        <legend class="sr-only">Locations</legend>
        <div class="relative flex items-start space-x-2 justify-center">
            @foreach($perimeter_locations as $location)
                <div class="flex items-center h-5">
                    <input id="{{ $location->location }}" wire:model="searchLocations.{{ $location->location }}" value="{{ $location->location }}" aria-describedby="{{ $location->location }}-description" type="checkbox" class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                </div>
                <div class="ml-3 text-sm">
                    <label for="{{ $location->location }}" class="font-medium text-gray-700">{{ $location->location }}</label>
                    <span id="{{ $location->location }}-description" class="text-gray-500"><span class="sr-only">{{ $location->location }} </span><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path stroke-linecap="round" stroke-linejoin="round" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg> {{ round($location->distance) }} km</span>
                </div>
            @endforeach
        </div>
    </fieldset>

    @if(count($courses))
        <div class="bg-white mt-3 shadow overflow-hidden sm:rounded-md">
            <ul role="list" class="divide-y divide-gray-200">
                @foreach($courses as $course)
                    <li>
                        <a @if(($course->seats - $course->participants_count) > 0)wire:click="showPrice({{ $course->id }})"@endif class="block hover:bg-gray-50">
                            <div class="px-4 py-4 sm:px-6">
                                <div class="flex items-center justify-between">
                                    <p class="text-sm font-medium text-indigo-600 truncate">{{ $courses[0]->type->name }}</p>
                                    <div class="ml-2 flex-shrink-0 flex">
                                        @if(percentage($course->seats, $course->participants_count) > config('booking.few_seats'))
                                            <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">{{ _i('free seats') }}</p>
                                        @elseif(percentage($course->seats, $course->participants_count) <= config('booking.few_seats') && ($course->seats - $course->participants_count) > 0)
                                            <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-300 text-yellow-800">{{ _i('few seats') }}</p>
                                        @else
                                            <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-300 text-red-800">{{ _i('booked out') }}</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="mt-2 sm:flex sm:justify-between">
                                    <div class="sm:flex">
                                        <p class="flex items-center text-sm text-gray-500">
                                            <!-- Heroicon name: solid/location-marker -->
                                            <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                                <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                                            </svg>
                                            {{ $course->street }}, {{ $course->zipcode }} {{ $course->location }}
                                        </p>
                                    </div>
                                    <div class="mt-2 flex items-center text-sm text-gray-500 sm:mt-0">
                                        <!-- Heroicon name: solid/calendar -->
                                        <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                            <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
                                        </svg>
                                        <p>
                                            <time datetime="{{ \Carbon\Carbon::parse($course->start)->isoFormat('YYYY-MM-DD') }}">{{ \Carbon\Carbon::parse($course->start)->isoFormat('DD.MM.YYYY, dd.') }} {{ \Carbon\Carbon::parse($course->start)->isoFormat('HH:mm') }} - {{ \Carbon\Carbon::parse($course->end)->isoFormat('HH:mm') }}</time>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                @endforeach
            </ul>
        </div>
    @else
        <p class="text-gray-500 text-center">{{ _i('aren\'t offered at the moment... Please try again with another location!') }}</p>
    @endif

    <x-booking.footer />

    <x-modal.dialog wire:model.defer="showPriceModal">
        <x-slot name="title"></x-slot>
        <x-slot name="content">
            <div class="max-w-7xl mx-auto py-12 px-4 bg-white sm:px-6 lg:px-8">
                <h2 class="text-2xl font-extrabold text-gray-900 sm:text-5xl sm:leading-none sm:tracking-tight lg:text-6xl">{{ _i('Our offers') }}</h2>
                <p class="mt-6 max-w-2xl text-xl text-gray-500">{{ _i('Choose the right offer for your course here.') }}</p>

                <div class="mt-12 space-y-0 lg:grid lg:grid-cols-2 lg:gap-x-8">
                    @foreach($actual->prices as $price)
                        <div class="relative p-8 bg-white border border-gray-200 rounded-2xl shadow-sm flex flex-col">
                            <div class="flex-1">
                                <h3 class="text-xl font-semibold text-gray-900">{{ $price->title }}</h3>
                                <p class="mt-4 flex items-baseline text-gray-900">
                                    <span class="text-3xl font-extrabold tracking-tight">{{ \App\Models\Price::SIGN[$price->currency] }} {{ $price->amount_gross }}</span>
                                    <span class="ml-1 text-xl font-semibold">/ {{ _i('Person') }}</span>
                                </p>
                                <p class="mt-6 text-gray-500">{{ $price->description }}</p>
                            </div>

                            <button wire:click="selectCourse({{ $actual->id }}, {{ $price->id }})" class="bg-indigo-500 text-white hover:bg-indigo-600 mt-8 block w-full py-3 px-6 border border-transparent rounded-md text-center font-medium">{{ _i('select') }}</button>
                        </div>

                    @endforeach
                </div>
            </div>
        </x-slot>
        <x-slot name="footer">
            <div class="text-xs">Preise inkl. MwSt</div>
        </x-slot>
    </x-modal.dialog>

</div>

resources/views/livewire/fcaptcha.blade.php
<div>
    <div>
        @unless($solved)
            <div>
                @error('validation') <div class="mt-1 flex justify-center text-sm text-red-500">{{ $message }}</div> @enderror
            </div>

            <div class="flex justify-center">
                <div class="frc-captcha flex justify-center" data-sitekey="{{ config('fcaptcha.sitekey') }}" data-callback="captchaSolved" data-lang="{{ app()->getLocale() }}"></div>
            </div>
        @endunless
    </div>

    <script>
        function captchaSolved(solution) {
            Livewire.emitTo('fcaptcha', 'captchaSolved', solution);
        }
    </script>

    {{-- remove captcha, if no friendly captcha key is present--}}
    @if(!config('fcaptcha.sitekey') || !config('fcaptcha.secret'))
        <div x-init="$wire.emit('removeCaptcha')"></div>
    @endif
</div>

resources/views/livewire/home.blade.php
<div>
    {{-- Replace with your content --}}
    <div class="py-4">
        <div class="h-96 rounded-lg border-4 border-dashed border-gray-200">

        </div>
    </div>
    {{-- /End replace --}}
</div>

resources/views/livewire/setup.blade.php
<div>
    <div class="flex min-h-screen items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
        <div class="w-full max-w-md space-y-8">
            <div wire:loading.remove wire:target="register">
                <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
                     alt="Workflow">
                <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                    {{ _i('add admin account') }}
                </h2>
                <p class="mt-2 text-center text-sm text-gray-600">
                    {{ _i('Whole database will be reset!') }}
                </p>
            </div>
            <form wire:submit.prevent="register" wire:loading.remove wire:target="register" class="mt-8 space-y-6">
                <input type="hidden" name="remember" value="true">
                <div class="-space-y-px rounded-md shadow-sm">
                    <div>
                        <label for="name" class="sr-only">{{ _i('name') }}</label>
                        <input wire:model.lazy="name" id="name" type="text" autocomplete="name" required
                               class="@error('name') border-red-500 text-red-900 placeholder-red-300 focus:border-red-500 focus:ring-red @enderror relative block w-full appearance-none rounded-none rounded-t-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-400 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                               placeholder="{{ _i('name') }}">
                    </div>
                    @error('name')
                        <div class="mt-1 flex justify-center text-center text-sm text-red-500">{{ $message }}</div>
                    @enderror

                    <div>
                        <label for="email-address" class="sr-only">{{ _i('Email address') }}</label>
                        <input wire:model.lazy="email" id="email-address" type="email" autocomplete="email" required
                               class="@error('email') border-red-500 text-red-900 placeholder-red-300 focus:border-red-500 focus:ring-red @enderror relative block w-full appearance-none rounded-none rounded-b-md border border-gray-300 px-3 py-2 text-gray-900 placeholder-gray-400 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm"
                               placeholder="{{ _i('Email address') }}">
                    </div>
                    @error('email')
                        <div class="mt-1 flex justify-center text-center text-sm text-red-500">{{ $message }}</div>
                    @enderror
                </div>

                <div>
                    <button type="submit"
                            class="group relative flex w-full justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                        <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                            <!-- Heroicon name: solid/lock-closed -->
                            <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg"
                                 viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                  d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                                  clip-rule="evenodd"/>
                            </svg>
                        </span>
                        {{ _i('add account') }}
                    </button>
                </div>
            </form>

            <div class="flex w-full justify-center text-center">
                <div wire:loading wire:target="register">
                    {{ _i('Processing ... Please wait ...') }}
                </div>
            </div>
        </div>
    </div>
</div>